version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 19.03.14
      - checkout
      - run: |
          git clone https://github.com/fmalmeida/bacannot.git
          cd bacannot
          cd docker
          export DOCKER_CLI_EXPERIMENTAL=enabled
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker context create my-context
          docker buildx create --use my-context
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 --tag fmalmeida/bacannot:v2.3_renv -f Dockerfile_renv .
