name: Build and push the base image of bacannot pipeline
# this github action builds the base image of bacannot pipeline
# the base image is the one that contains all the tools used in the main
# workflow of the pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub (release)
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: download github repo
        run: |
          git clone https://github.com/fmalmeida/bacannot.git
          curl --silent "https://api.github.com/repos/fmalmeida/bacannot/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' > LATEST_RELEASE

      - name: Build docker images
        run: |
          cd bacannot/docker
          docker build --no-cache -t fmalmeida/bacannot_base:$(cat LATEST_RELEASE) -f Dockerfile_main_tools .

      - name: Push Docker image to DockerHub (all)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push fmalmeida/bacannot_base:$(cat LATEST_RELEASE)
