name: (multi-arch) latest bacannot
# this github action builds the base image of bacannot pipeline
# the base image is the one that contains all the tools used in the main
# workflow of the pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub (release)
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fmalmeida
          repo: bacannot
          excludes: prerelease, draft
      
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: download github repo
        run: |
          git clone https://github.com/fmalmeida/bacannot.git
      
      - name: Build and push docker image
        run: |
          cd bacannot/docker
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker buildx create --use
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag fmalmeida/bacannot:${{ steps.keydb.outputs.release }} -f Dockerfile_bacannot .
#          docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 --tag fmalmeida/bacannot:${{ steps.keydb.outputs.release }} -f Dockerfile_bacannot .
