name: docker build and push (main image containing database files)
# This builds and push the docker images to dockerhub
# designed to build the main image containing the main databases once every month (or when dispatched manually)
# in order to either maintain the databases up-to-date
# Docker images affected: bacannot:latest
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub (release)
    runs-on: ubuntu-latest
    # Only run for the nf-core repo, for releases and merged PRs
    if: ${{ github.repository == 'fmalmeida/bacannot' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker build --no-cache -t fmalmeida/bacannot:latest -f Dockerfile_bacannot ./docker

      - name: Push Docker image to DockerHub (all)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push fmalmeida/bacannot:latest
#          docker tag nfcore/eager:latest nfcore/eager:${{ github.event.release.tag_name }}
#          docker push nfcore/eager:${{ github.event.release.tag_name }}
