name: docker pull (skeleton images)
# Pull images every 6 months to keep them active in dockerhub
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'

jobs:
  push_dockerhub:
    name: Pull docker images
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fmalmeida
          repo: bacannot
          excludes: prerelease, draft
          
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Pull Docker image from DockerHub (all)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker pull fmalmeida/bacannot:main_tools
          docker rmi -f fmalmeida/bacannot:main_tools
          dpcler pull fmalmeida/bacannot:${{ steps.keydb.outputs.release }}
          docker rmi -f fmalmeida/bacannot:${{ steps.keydb.outputs.release }}
          docker pull fmalmeida/bacannot:${{ steps.keydb.outputs.release }}_renv
          docker rmi -f fmalmeida/bacannot:${{ steps.keydb.outputs.release }}_renv
          docker pull fmalmeida/bacannot:jbrowse
          docker rmi -f fmalmeida/bacannot:jbrowse
          docker pull fmalmeida/bacannot:kofamscan
          docker rmi -f fmalmeida/bacannot:kofamscan
